---
- name: add repository for docker ce
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    file: docker-ce
- name: install packages
  yum: name={{item}}
  with_items:
    - docker-ce
    - device-mapper-persistent-data
    - lvm2
    - nfs-utils
    - python-docker-py
- name: enable and start docker
  service: name=docker state=started enabled=yes
