---
- tasks:
    - name: docker network set
      command: docker network create --driver bridge \
           --ipv6 --subnet 2001:da8:a0:500:beaf::/80 \
           --ip-range 2001:da8:a0:500:beaf::/100 prometheus
   
    - name: create volumn1
      command: mkdir /opt/altermanager

    - name: create volumn2
      command: mkdir /opt/prometheus

    - name: create volumn3
      command: mkdir /opt/grafana

    - name: docker volumn create1
      command: docker volume create --driver local \
           --name alertmanager --opt device=/opt/alertmanager \ 
           --opt type=none --opt o=bind

    - name: docker volumn create2
      command: docker volume create --driver local \
           --name prometheus --opt device=/opt/prometheus \
           --opt type=none --opt o=bind

    - name: docker volumn create3
      command: docker volume create --driver local \
           --name grafana --opt device=/opt/grafana \
           --opt type=none --opt o=bind
