public:
  walk:
  - 1.3.6.1.2.1.1
  - 1.3.6.1.2.1.2.2
  - 1.3.6.1.2.1.31
  metrics:
  - name: sysDescr
    oid: 1.3.6.1.2.1.1.1
    type: DisplayString
    help: A textual description of the entity - 1.3.6.1.2.1.1.1
  - name: sysUpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
    help: The time (in hundredths of a second) since the network management portion
      of the system was last re-initialized. - 1.3.6.1.2.1.1.3
  - name: sysContact
    oid: 1.3.6.1.2.1.1.4
    type: DisplayString
    help: The textual identification of the contact person for this managed node,
      together with information on how to contact this person - 1.3.6.1.2.1.1.4
  - name: sysName
    oid: 1.3.6.1.2.1.1.5
    type: DisplayString
    help: An administratively-assigned name for this managed node - 1.3.6.1.2.1.1.5
  - name: sysLocation
    oid: 1.3.6.1.2.1.1.6
    type: DisplayString
    help: The physical location of this node (e.g., 'telephone closet, 3rd floor')
      - 1.3.6.1.2.1.1.6
  - name: sysServices
    oid: 1.3.6.1.2.1.1.7
    type: gauge
    help: A value which indicates the set of services that this entity may potentially
      offer - 1.3.6.1.2.1.1.7
  - name: sysORLastChange
    oid: 1.3.6.1.2.1.1.8
    type: gauge
    help: The value of sysUpTime at the time of the most recent change in state or
      value of any instance of sysORID. - 1.3.6.1.2.1.1.8
  - name: sysORIndex
    oid: 1.3.6.1.2.1.1.9.1.1
    type: gauge
    help: The auxiliary variable used for identifying instances of the columnar objects
      in the sysORTable. - 1.3.6.1.2.1.1.9.1.1
    indexes:
    - labelname: sysORIndex
      type: gauge
  - name: sysORDescr
    oid: 1.3.6.1.2.1.1.9.1.3
    type: DisplayString
    help: A textual description of the capabilities identified by the corresponding
      instance of sysORID. - 1.3.6.1.2.1.1.9.1.3
    indexes:
    - labelname: sysORIndex
      type: gauge
  - name: sysORUpTime
    oid: 1.3.6.1.2.1.1.9.1.4
    type: gauge
    help: The value of sysUpTime at the time this conceptual row was last instantiated.
      - 1.3.6.1.2.1.1.9.1.4
    indexes:
    - labelname: sysORIndex
      type: gauge
  - name: ifIndex
    oid: 1.3.6.1.2.1.2.2.1.1
    type: gauge
    help: A unique value, greater than zero, for each interface - 1.3.6.1.2.1.2.2.1.1
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifDescr
    oid: 1.3.6.1.2.1.2.2.1.2
    type: DisplayString
    help: A textual string containing information about the interface - 1.3.6.1.2.1.2.2.1.2
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifType
    oid: 1.3.6.1.2.1.2.2.1.3
    type: gauge
    help: The type of interface - 1.3.6.1.2.1.2.2.1.3
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifMtu
    oid: 1.3.6.1.2.1.2.2.1.4
    type: gauge
    help: The size of the largest packet which can be sent/received on the interface,
      specified in octets - 1.3.6.1.2.1.2.2.1.4
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifSpeed
    oid: 1.3.6.1.2.1.2.2.1.5
    type: gauge
    help: An estimate of the interface's current bandwidth in bits per second - 1.3.6.1.2.1.2.2.1.5
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifPhysAddress
    oid: 1.3.6.1.2.1.2.2.1.6
    type: PhysAddress48
    help: The interface's address at its protocol sub-layer - 1.3.6.1.2.1.2.2.1.6
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifAdminStatus
    oid: 1.3.6.1.2.1.2.2.1.7
    type: gauge
    help: The desired state of the interface - 1.3.6.1.2.1.2.2.1.7
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOperStatus
    oid: 1.3.6.1.2.1.2.2.1.8
    type: gauge
    help: The current operational state of the interface - 1.3.6.1.2.1.2.2.1.8
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifLastChange
    oid: 1.3.6.1.2.1.2.2.1.9
    type: gauge
    help: The value of sysUpTime at the time the interface entered its current operational
      state - 1.3.6.1.2.1.2.2.1.9
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifInOctets
    oid: 1.3.6.1.2.1.2.2.1.10
    type: counter
    help: The total number of octets received on the interface, including framing
      characters - 1.3.6.1.2.1.2.2.1.10
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifInUcastPkts
    oid: 1.3.6.1.2.1.2.2.1.11
    type: counter
    help: The number of packets, delivered by this sub-layer to a higher (sub-)layer,
      which were not addressed to a multicast or broadcast address at this sub-layer
      - 1.3.6.1.2.1.2.2.1.11
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifInNUcastPkts
    oid: 1.3.6.1.2.1.2.2.1.12
    type: counter
    help: The number of packets, delivered by this sub-layer to a higher (sub-)layer,
      which were addressed to a multicast or broadcast address at this sub-layer -
      1.3.6.1.2.1.2.2.1.12
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifInDiscards
    oid: 1.3.6.1.2.1.2.2.1.13
    type: counter
    help: The number of inbound packets which were chosen to be discarded even though
      no errors had been detected to prevent their being deliverable to a higher-layer
      protocol - 1.3.6.1.2.1.2.2.1.13
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifInErrors
    oid: 1.3.6.1.2.1.2.2.1.14
    type: counter
    help: For packet-oriented interfaces, the number of inbound packets that contained
      errors preventing them from being deliverable to a higher-layer protocol - 1.3.6.1.2.1.2.2.1.14
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifInUnknownProtos
    oid: 1.3.6.1.2.1.2.2.1.15
    type: counter
    help: For packet-oriented interfaces, the number of packets received via the interface
      which were discarded because of an unknown or unsupported protocol - 1.3.6.1.2.1.2.2.1.15
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOutOctets
    oid: 1.3.6.1.2.1.2.2.1.16
    type: counter
    help: The total number of octets transmitted out of the interface, including framing
      characters - 1.3.6.1.2.1.2.2.1.16
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOutUcastPkts
    oid: 1.3.6.1.2.1.2.2.1.17
    type: counter
    help: The total number of packets that higher-level protocols requested be transmitted,
      and which were not addressed to a multicast or broadcast address at this sub-layer,
      including those that were discarded or not sent - 1.3.6.1.2.1.2.2.1.17
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOutNUcastPkts
    oid: 1.3.6.1.2.1.2.2.1.18
    type: counter
    help: The total number of packets that higher-level protocols requested be transmitted,
      and which were addressed to a multicast or broadcast address at this sub-layer,
      including those that were discarded or not sent - 1.3.6.1.2.1.2.2.1.18
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOutDiscards
    oid: 1.3.6.1.2.1.2.2.1.19
    type: counter
    help: The number of outbound packets which were chosen to be discarded even though
      no errors had been detected to prevent their being transmitted - 1.3.6.1.2.1.2.2.1.19
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOutErrors
    oid: 1.3.6.1.2.1.2.2.1.20
    type: counter
    help: For packet-oriented interfaces, the number of outbound packets that could
      not be transmitted because of errors - 1.3.6.1.2.1.2.2.1.20
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOutQLen
    oid: 1.3.6.1.2.1.2.2.1.21
    type: gauge
    help: The length of the output packet queue (in packets). - 1.3.6.1.2.1.2.2.1.21
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifTableLastChange
    oid: 1.3.6.1.2.1.31.1.5
    type: gauge
    help: The value of sysUpTime at the time of the last creation or deletion of an
      entry in the ifTable - 1.3.6.1.2.1.31.1.5
  - name: ifName
    oid: 1.3.6.1.2.1.31.1.1.1.1
    type: DisplayString
    help: The textual name of the interface - 1.3.6.1.2.1.31.1.1.1.1
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifInMulticastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.2
    type: counter
    help: The number of packets, delivered by this sub-layer to a higher (sub-)layer,
      which were addressed to a multicast address at this sub-layer - 1.3.6.1.2.1.31.1.1.1.2
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifInBroadcastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.3
    type: counter
    help: The number of packets, delivered by this sub-layer to a higher (sub-)layer,
      which were addressed to a broadcast address at this sub-layer - 1.3.6.1.2.1.31.1.1.1.3
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOutMulticastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.4
    type: counter
    help: The total number of packets that higher-level protocols requested be transmitted,
      and which were addressed to a multicast address at this sub-layer, including
      those that were discarded or not sent - 1.3.6.1.2.1.31.1.1.1.4
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOutBroadcastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.5
    type: counter
    help: The total number of packets that higher-level protocols requested be transmitted,
      and which were addressed to a broadcast address at this sub-layer, including
      those that were discarded or not sent - 1.3.6.1.2.1.31.1.1.1.5
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCInOctets
    oid: 1.3.6.1.2.1.31.1.1.1.6
    type: counter
    help: The total number of octets received on the interface, including framing
      characters - 1.3.6.1.2.1.31.1.1.1.6
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCInUcastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.7
    type: counter
    help: The number of packets, delivered by this sub-layer to a higher (sub-)layer,
      which were not addressed to a multicast or broadcast address at this sub-layer
      - 1.3.6.1.2.1.31.1.1.1.7
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCInMulticastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.8
    type: counter
    help: The number of packets, delivered by this sub-layer to a higher (sub-)layer,
      which were addressed to a multicast address at this sub-layer - 1.3.6.1.2.1.31.1.1.1.8
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCInBroadcastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.9
    type: counter
    help: The number of packets, delivered by this sub-layer to a higher (sub-)layer,
      which were addressed to a broadcast address at this sub-layer - 1.3.6.1.2.1.31.1.1.1.9
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCOutOctets
    oid: 1.3.6.1.2.1.31.1.1.1.10
    type: counter
    help: The total number of octets transmitted out of the interface, including framing
      characters - 1.3.6.1.2.1.31.1.1.1.10
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCOutUcastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.11
    type: counter
    help: The total number of packets that higher-level protocols requested be transmitted,
      and which were not addressed to a multicast or broadcast address at this sub-layer,
      including those that were discarded or not sent - 1.3.6.1.2.1.31.1.1.1.11
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCOutMulticastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.12
    type: counter
    help: The total number of packets that higher-level protocols requested be transmitted,
      and which were addressed to a multicast address at this sub-layer, including
      those that were discarded or not sent - 1.3.6.1.2.1.31.1.1.1.12
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCOutBroadcastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.13
    type: counter
    help: The total number of packets that higher-level protocols requested be transmitted,
      and which were addressed to a broadcast address at this sub-layer, including
      those that were discarded or not sent - 1.3.6.1.2.1.31.1.1.1.13
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifLinkUpDownTrapEnable
    oid: 1.3.6.1.2.1.31.1.1.1.14
    type: gauge
    help: Indicates whether linkUp/linkDown traps should be generated for this interface
      - 1.3.6.1.2.1.31.1.1.1.14
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHighSpeed
    oid: 1.3.6.1.2.1.31.1.1.1.15
    type: gauge
    help: An estimate of the interface's current bandwidth in units of 1,000,000 bits
      per second - 1.3.6.1.2.1.31.1.1.1.15
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifPromiscuousMode
    oid: 1.3.6.1.2.1.31.1.1.1.16
    type: gauge
    help: This object has a value of false(2) if this interface only accepts packets/frames
      that are addressed to this station - 1.3.6.1.2.1.31.1.1.1.16
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifConnectorPresent
    oid: 1.3.6.1.2.1.31.1.1.1.17
    type: gauge
    help: This object has the value 'true(1)' if the interface sublayer has a physical
      connector and the value 'false(2)' otherwise. - 1.3.6.1.2.1.31.1.1.1.17
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifAlias
    oid: 1.3.6.1.2.1.31.1.1.1.18
    type: DisplayString
    help: This object is an 'alias' name for the interface as specified by a network
      manager, and provides a non-volatile 'handle' for the interface - 1.3.6.1.2.1.31.1.1.1.18
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifCounterDiscontinuityTime
    oid: 1.3.6.1.2.1.31.1.1.1.19
    type: gauge
    help: The value of sysUpTime on the most recent occasion at which any one or more
      of this interface's counters suffered a discontinuity - 1.3.6.1.2.1.31.1.1.1.19
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifStackHigherLayer
    oid: 1.3.6.1.2.1.31.1.2.1.1
    type: gauge
    help: The value of ifIndex corresponding to the higher sub-layer of the relationship,
      i.e., the sub-layer which runs on 'top' of the sub-layer identified by the corresponding
      instance of ifStackLowerLayer - 1.3.6.1.2.1.31.1.2.1.1
    indexes:
    - labelname: ifStackHigherLayer
      type: gauge
    - labelname: ifStackLowerLayer
      type: gauge
  - name: ifStackLowerLayer
    oid: 1.3.6.1.2.1.31.1.2.1.2
    type: gauge
    help: The value of ifIndex corresponding to the lower sub-layer of the relationship,
      i.e., the sub-layer which runs 'below' the sub-layer identified by the corresponding
      instance of ifStackHigherLayer - 1.3.6.1.2.1.31.1.2.1.2
    indexes:
    - labelname: ifStackHigherLayer
      type: gauge
    - labelname: ifStackLowerLayer
      type: gauge
  - name: ifStackStatus
    oid: 1.3.6.1.2.1.31.1.2.1.3
    type: gauge
    help: The status of the relationship between two sub-layers - 1.3.6.1.2.1.31.1.2.1.3
    indexes:
    - labelname: ifStackHigherLayer
      type: gauge
    - labelname: ifStackLowerLayer
      type: gauge
  - name: ifStackLastChange
    oid: 1.3.6.1.2.1.31.1.6
    type: gauge
    help: The value of sysUpTime at the time of the last change of the (whole) interface
      stack - 1.3.6.1.2.1.31.1.6
  - name: ifRcvAddressAddress
    oid: 1.3.6.1.2.1.31.1.4.1.1
    type: PhysAddress48
    help: An address for which the system will accept packets/frames on this entry's
      interface. - 1.3.6.1.2.1.31.1.4.1.1
    indexes:
    - labelname: ifIndex
      type: gauge
    - labelname: ifRcvAddressAddress
      type: PhysAddress48
  - name: ifRcvAddressStatus
    oid: 1.3.6.1.2.1.31.1.4.1.2
    type: gauge
    help: This object is used to create and delete rows in the ifRcvAddressTable.
      - 1.3.6.1.2.1.31.1.4.1.2
    indexes:
    - labelname: ifIndex
      type: gauge
    - labelname: ifRcvAddressAddress
      type: PhysAddress48
  - name: ifRcvAddressType
    oid: 1.3.6.1.2.1.31.1.4.1.3
    type: gauge
    help: This object has the value nonVolatile(3) for those entries in the table
      which are valid and will not be deleted by the next restart of the managed system
      - 1.3.6.1.2.1.31.1.4.1.3
    indexes:
    - labelname: ifIndex
      type: gauge
    - labelname: ifRcvAddressAddress
      type: PhysAddress48
  - name: ifTestId
    oid: 1.3.6.1.2.1.31.1.3.1.1
    type: gauge
    help: This object identifies the current invocation of the interface's test. -
      1.3.6.1.2.1.31.1.3.1.1
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifTestStatus
    oid: 1.3.6.1.2.1.31.1.3.1.2
    type: gauge
    help: This object indicates whether or not some manager currently has the necessary
      'ownership' required to invoke a test on this interface - 1.3.6.1.2.1.31.1.3.1.2
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifTestResult
    oid: 1.3.6.1.2.1.31.1.3.1.4
    type: gauge
    help: This object contains the result of the most recently requested test, or
      the value none(1) if no tests have been requested since the last reset - 1.3.6.1.2.1.31.1.3.1.4
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifTestOwner
    oid: 1.3.6.1.2.1.31.1.3.1.6
    type: DisplayString
    help: The entity which currently has the 'ownership' required to invoke a test
      on this interface. - 1.3.6.1.2.1.31.1.3.1.6
    indexes:
    - labelname: ifIndex
      type: gauge
